### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by HassanAzzam** [ChristianBecker/inkscape-android-export#4]
Is it compatible with Windows OS?!

**Comment by ChristianBecker** [comment]
Unfortunately its not compatible with Windows without adjustments. But I'm open for contributions!

**Comment by HassanAzzam** [comment]
I think the only problem is the path for exporting.

**Comment by ChristianBecker** [comment]
Another problem could be the usage of OptiPNG: We simply execute `convert` and assume that this command is available on the `PATH`. This has to be adjusted for Windows, too…
